const items = [
    {
        id: '001',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsHIAXAbU7o7FahB8oQGOySt7yg7hK0b7EbP3ENBstAyrus-Nq0jun9w6wvltWY7P6zag&usqp=CAU',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: 'https://m.media-amazon.com/images/I/91WLT0sWaFL._AC_UY1000_.jpg',
        company: 'Beyove',
        item_name: 'Womens Ditsy Floral Dress Long Sleeve Dress',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS5nd4LR1hI8O2Bjl4CgkLlt2Agr6mpNZ9yY-AEQcMcYW2F8zAqdXW9p2_x692pEFvgt9aE32_EWHUTZuibhrYiaOT8pfBVFf1YL8pIm8o&usqp=CAE',
        company: 'Tartan',
        item_name: 'Modern plaid shirt for women',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQmW6BVN804qQ-DSCDzzrU2eapkeKooTVjKkuyOD7osqXye0ThHIXZmV1hVF-YLf_qjtAzMv8hw_h10BhkWLX3wjgo7xciQ5_9XnqHNOo8KQNxcNCxVdUBC9A&usqp=CAE',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'https://assets.myntassets.com/assets/images/21423424/2023/4/18/62417b3e-260a-4e0f-98b3-5315be4081d71681807238460-Roadster-Men-Tshirts-6951681807237921-1.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'https://5.imimg.com/data5/SELLER/Default/2020/9/PR/TC/WZ/113537169/dfteqslwkaaorom-500x500.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'https://m.media-amazon.com/images/I/71Q+ws9aTRL.jpg',
        company: 'COVEGE',
        item_name: 'Buy Pink Vase for Flowers - Handmade Mosaic Glass Vase',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'https://fimgs.net/mdimg/secundar/o.85513.jpg',
        company: 'Judith Williams',
        item_name: 'Judith Williams Perfumery Beautiful EDP 30ml',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
];